### ISSUE TITLE
remove unnecessary print statement

### ISSUE THREAD

**Issue by siruku6** [siruku6/oanda_accessor_pyv20#7]
This line is to be removed.

https://github.com/siruku6/oanda_accessor_pyv20/blob/c24b5191c41b52e6e7f6546874b13d475b8f1c98/oanda_accessor_pyv20/api.py#L120

**Comment by DamyanBG** [comment]
Please, assign.

**Comment by siruku6** [comment]
@DamyanBG 
OK, please fix it.

**Comment by DamyanBG** [comment]
OK

**Comment by siruku6** [comment]
Thank you!
